# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk < Formula
  desc "A simple task runner and build tool with TOML configuration."
  homepage "https://github.com/notnmeyer/tsk"
  version "0.9.3"

  on_macos do
    on_intel do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.3/tsk_v0.9.3_Darwin_x86_64.tar.gz"
      sha256 "e639de908774ea886ab0942d812b120ec4ec92252d8655b7e0be4a12273644f1"

      def install
        bin.install "tsk"
      end
    end
    on_arm do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.3/tsk_v0.9.3_Darwin_arm64.tar.gz"
      sha256 "8618a465a3241b020d26986098ffd4965423958bcd4b1f2a6dc0245a888592bc"

      def install
        bin.install "tsk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.3/tsk_v0.9.3_Linux_x86_64.tar.gz"
        sha256 "41108898f55706ed1f158ddd974ce23df42295d809c89a2fd56d5707656c44ee"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.3/tsk_v0.9.3_Linux_arm_6.tar.gz"
        sha256 "368f20fa5b9210aaefefb8d1795c9db0b7eb60efc0d4312f3e65ded0a817bff3"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.3/tsk_v0.9.3_Linux_arm64.tar.gz"
        sha256 "47431bd3d6898dffe54cc895b1c7b817f55cf6855c7a77cfa64c25f7326cc477"

        def install
          bin.install "tsk"
        end
      end
    end
  end
end
