# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk < Formula
  desc "A simple task runner and build tool with TOML configuration."
  homepage "https://github.com/notnmeyer/tsk"
  version "0.9.1"

  on_macos do
    on_intel do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.1/tsk_v0.9.1_Darwin_x86_64.tar.gz"
      sha256 "2a0527e6a659f3947e73484395b2d2ef7f6eeca26fd9781c7c9a8dd6d5d462e6"

      def install
        bin.install "tsk"
      end
    end
    on_arm do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.1/tsk_v0.9.1_Darwin_arm64.tar.gz"
      sha256 "c70ed81b3f9ded4d094b8817786a69f70afbe46da4701cc3ac88a39a9db31029"

      def install
        bin.install "tsk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.1/tsk_v0.9.1_Linux_x86_64.tar.gz"
        sha256 "abdab34c377104f596d7332e3466241d657758737d2d7f1d6130a692091c38a1"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.1/tsk_v0.9.1_Linux_arm_6.tar.gz"
        sha256 "e5fa697a77dc0c418a048c48372b7998e1ea9efe6428760bbf7962cb8ed97b38"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.1/tsk_v0.9.1_Linux_arm64.tar.gz"
        sha256 "b579966b3cd4879193f16b9b941cdfe503bd30682406944a293e298d5765d602"

        def install
          bin.install "tsk"
        end
      end
    end
  end
end
