# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk < Formula
  desc "A simple task runner and build tool with TOML configuration."
  homepage "https://github.com/notnmeyer/tsk"
  version "0.9.0"

  on_macos do
    on_intel do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.0/tsk_v0.9.0_Darwin_x86_64.tar.gz"
      sha256 "884196b44d324a1bc5f46af3212038426f7212c8d5a68959c27bf7e844942070"

      def install
        bin.install "tsk"
      end
    end
    on_arm do
      url "https://github.com/notnmeyer/tsk/releases/download/v0.9.0/tsk_v0.9.0_Darwin_arm64.tar.gz"
      sha256 "dc231eb35c874f0582198ebc49889425ab5b360f4c2819f2e6f0a288434a0082"

      def install
        bin.install "tsk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.0/tsk_v0.9.0_Linux_x86_64.tar.gz"
        sha256 "814fa300f250c6ae999e9637298d4e72a61f9f12fed4f984227eb579a6afa297"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.0/tsk_v0.9.0_Linux_arm_6.tar.gz"
        sha256 "9f13bdf3d61fed2aab3e6436cf37bfbc61930c5f0c29478aceccc3ff2b8d9452"

        def install
          bin.install "tsk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/notnmeyer/tsk/releases/download/v0.9.0/tsk_v0.9.0_Linux_arm64.tar.gz"
        sha256 "fa3ce9be253f709cd116f0919ef32cac59113e62569e58a0bee1c1aa8f86ea79"

        def install
          bin.install "tsk"
        end
      end
    end
  end
end
